default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'read_the_ft_serverless_development' %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'read_the_ft_serverless_development' %>

test:
  <<: *default
  database: read_the_ft_serverless_test

production:
  <<: *default
  database: read_the_ft_serverless_production
  url: <%= ENV['DATABASE_URL'] %>
